In [1]:
import pandas as pd
df=pd.read_csv("Downloads/custdata.tsv", sep="\t")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   custid        1000 non-null   int64
 1   sex           1000 non-null   str
 2   is.employed   672 non-null    object
 3   income        1000 non-null   int64
 4   marital.stat  1000 non-null   str
 5   health.ins    1000 non-null   bool
 6   housing.type  944 non-null    str
 7   recent.move   944 non-null    object
 8   num.vehicles  944 non-null    float64
 9   age           1000 non-null   float64
 10  state.of.res  1000 non-null   str
dtypes: bool(1), float64(2), int64(2), object(2), str(4)
memory usage: 115.8+ KB

In [3]:
df.info

<bound method DataFrame.info of       custid sex is.employed  income        marital.stat  health.ins  \
0       2068   F         NaN   11300             Married        True
1       2073   F         NaN       0             Married        True
2       2848   M        True    4500       Never Married       False
3       5641   M        True   20000       Never Married       False
4       6369   F        True   12000       Never Married        True
..       ...  ..         ...     ...                 ...         ...
995  1411132   F       False   46000  Divorced/Separated        True
996  1411860   F         NaN    5400             Widowed        True
997  1412161   M        True   38500             Married        True
998  1412971   M         NaN   43400             Married        True
999  1414286   F       False   20900             Married       False

                 housing.type recent.move  num.vehicles   age  state.of.res
0    Homeowner free and clear       False           2.0  49.0      Michigan
1                      Rented        True           3.0  40.0       Florida
2                      Rented        True           3.0  22.0       Georgia
3       Occupied with no rent       False           0.0  22.0    New Mexico
4                      Rented        True           1.0  31.0       Florida
..                        ...         ...           ...   ...           ...
995                    Rented        True           1.0  56.0       Florida
996                       NaN         NaN           NaN  89.0  Pennsylvania
997                    Rented        True           1.0  29.0       Georgia
998  Homeowner free and clear       False           1.0  88.0          Ohio
999                    Rented       False           2.0  36.0      New York

[1000 rows x 11 columns]>

In [4]:
df.isnull().sum()

custid            0
sex               0
is.employed     328
income            0
marital.stat      0
health.ins        0
housing.type     56
recent.move      56
num.vehicles     56
age               0
state.of.res      0
dtype: int64

In [5]:
df.describe()

             custid         income  num.vehicles          age
count  1.000000e+03    1000.000000    944.000000  1000.000000
mean   6.984997e+05   53504.771000      1.916314    51.699815
std    4.135083e+05   65478.065729      1.101618    18.863433
min    2.068000e+03   -8700.000000      0.000000     0.000000
25%    3.456668e+05   14600.000000      1.000000    38.000000
50%    6.934030e+05   35000.000000      2.000000    50.000000
75%    1.044606e+06   67000.000000      2.000000    64.000000
max    1.414286e+06  615000.000000      6.000000   146.680197

In [6]:
#markdown cell
#there are no missing numbers for age,income, but 56 are missing from vehicles
#there is a discrepency to the income as there is a low min of -8700 so it could be a typo or mistake
#there is a discrepancy in the age as well with customers being babies and older data point at 146 years old

In [7]:
cols = ["age","income","num.vehicles"]

In [8]:
corr_before=df[cols].corr()

In [9]:
print(corr_before)

                   age    income  num.vehicles
age           1.000000  0.027429     -0.063666
income        0.027429  1.000000      0.139198
num.vehicles -0.063666  0.139198      1.000000

In [10]:
cleaned_df = df[(df["age"] >= 18) & (df["age"] <= 100)]
cleaned_df = cleaned_df[cleaned_df["income"] >= 0]

In [11]:
#edits
#removed age where there was possible errors, removing anyone under the age of 18 an above 100 years old
#removed income of anyone less than 0, or making negative income, for analysis

In [12]:
cleaned_df.describe()

             custid         income  num.vehicles         age
count  9.880000e+02     988.000000    932.000000  988.000000
mean   6.958594e+05   53129.879555      1.914163   51.215587
std    4.132938e+05   65200.621337      1.103229   17.363014
min    2.068000e+03       0.000000      0.000000   18.000000
25%    3.430412e+05   14575.000000      1.000000   38.000000
50%    6.886580e+05   35000.000000      2.000000   50.000000
75%    1.042425e+06   66250.000000      2.000000   63.000000
max    1.414286e+06  615000.000000      6.000000   93.000000

In [13]:
#verified cleaned_df has removed age values above 100 and below 18, thus removing 12 rows from ages
#verified income also removed incomes that were impossible and was removed with age as the total numbe for income match age count

In [14]:
cols = ["age","income","num.vehicles"]
corr_after=cleaned_df[cols].corr()
print(corr_after)

                   age    income  num.vehicles
age           1.000000  0.008881     -0.066295
income        0.008881  1.000000      0.137859
num.vehicles -0.066295  0.137859      1.000000

In [15]:
#Correlation statement
# there is an r value of .137 between income and number of vehicles pointing to higher incomes to having more cars.
# the r value of .008 between income and age shows theres no relationship between ones age and income made.